"""Provenance check."""

from __future__ import annotations

from typing import Dict, List


_KNOWN_WATERMARKS = [
    "openai",
    "gpt",
    "assistant",
    "watermark",
    "generated by",
    "model signature",
]


def scan(text: str) -> Dict[str, object]:
    """Scan for simple textual watermark indicators."""
    if not text:
        return {"watermarks": [], "detected": False}

    lowered = text.lower()
    found: List[str] = []
    for marker in _KNOWN_WATERMARKS:
        if marker in lowered:
            found.append(marker)

    return {
        "watermarks": found,
        "detected": bool(found),
    }
